#include <pebble.h>

#define ENGLISH_LANGUAGE 0
#define RUSSIAN_LANGUAGE 1

#define DD_MM_YYYY_DATE_FORMAT 0
#define DD_MMMM_DATE_FORMAT 1

#define SMALL_TIME_TEXT 0
#define BIG_TIME_TEXT 1

#define NORMAL_COLOR 0
#define INVERTED_COLOR 1

static const uint32_t battery_ccons[2][12] = {
	{
		RESOURCE_ID_BATTERY_0_NORMAL, 
		RESOURCE_ID_BATTERY_10_NORMAL, 
		RESOURCE_ID_BATTERY_20_NORMAL, 
		RESOURCE_ID_BATTERY_30_NORMAL, 
		RESOURCE_ID_BATTERY_40_NORMAL, 
		RESOURCE_ID_BATTERY_50_NORMAL, 
		RESOURCE_ID_BATTERY_60_NORMAL, 
		RESOURCE_ID_BATTERY_70_NORMAL, 
		RESOURCE_ID_BATTERY_80_NORMAL, 
		RESOURCE_ID_BATTERY_90_NORMAL,
		RESOURCE_ID_BATTERY_100_NORMAL,
		RESOURCE_ID_BATTERY_FULL_NORMAL
	},
	{
		RESOURCE_ID_BATTERY_0_INVERTED, 
		RESOURCE_ID_BATTERY_10_INVERTED, 
		RESOURCE_ID_BATTERY_20_INVERTED, 
		RESOURCE_ID_BATTERY_30_INVERTED, 
		RESOURCE_ID_BATTERY_40_INVERTED, 
		RESOURCE_ID_BATTERY_50_NORMAL, 
		RESOURCE_ID_BATTERY_60_NORMAL, 
		RESOURCE_ID_BATTERY_70_NORMAL, 
		RESOURCE_ID_BATTERY_80_INVERTED, 
		RESOURCE_ID_BATTERY_90_INVERTED,
		RESOURCE_ID_BATTERY_100_INVERTED,
		RESOURCE_ID_BATTERY_FULL_INVERTED
	}
};

static const uint32_t bluetooth_icons[2][2] = {
	{
		RESOURCE_ID_BLUETOOTH_NO_NORMAL,
		RESOURCE_ID_BLUETOOTH_YES_NORMAL
	},
	{
		RESOURCE_ID_BLUETOOTH_NO_INVERTED,
		RESOURCE_ID_BLUETOOTH_YES_INVERTED
	}
};

